// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceNowCM.Infrastructure.Persistence;

#nullable disable

namespace ServiceNowCM.Infrastructure.Migrations
{
    [DbContext(typeof(ServiceNowCMDbContext))]
    [Migration("20260904073611_AddSyncFailures")]
    partial class AddSyncFailures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServiceNowCM.Domain.Entities.ContentManagerConnection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AuthenticationType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CredentialReference")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DatasetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WorkgroupServerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("WorkgroupServerPort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ContentManagerConnections", "config");
                });

            modelBuilder.Entity("ServiceNowCM.Domain.Entities.IntegrationConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ContentManagerConnectionId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentManagerRecordTypeName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("ContentManagerRecordTypeUri")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DisplayValues")
                        .HasColumnType("bit");

                    b.Property<string>("EncodedQuery")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("ExcludeReferenceLinks")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PageSize")
                        .HasColumnType("int");

                    b.Property<int>("ProcessingBatchSize")
                        .HasColumnType("int");

                    b.Property<long>("ServiceNowConnectionId")
                        .HasColumnType("bigint");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ContentManagerConnectionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ServiceNowConnectionId");

                    b.ToTable("Integrations", "config");
                });

            modelBuilder.Entity("ServiceNowCM.Domain.Entities.IntegrationField", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<long>("IntegrationConfigurationId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceFieldDataType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceFieldLabel")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SourceFieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TargetFieldName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TargetFieldType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("TargetFieldUri")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationConfigurationId", "SourceFieldName")
                        .IsUnique();

                    b.ToTable("IntegrationFields", "config");
                });

            modelBuilder.Entity("ServiceNowCM.Domain.Entities.ServiceNowConnection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AuthenticationType")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CredentialReference")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InstanceUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ServiceNowConnections", "config");
                });

            modelBuilder.Entity("ServiceNowCM.Domain.Entities.StoredCredential", b =>
                {
                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EncryptedSecret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Reference");

                    b.ToTable("Credentials", "security");
                });

            modelBuilder.Entity("ServiceNowCM.Domain.Entities.SyncFailure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<long?>("ContentManagerRecordUri")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long>("IntegrationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceRecordNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceSysId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("SyncJobId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationId");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("SyncJobId");

                    b.HasIndex("IntegrationId", "IsResolved");

                    b.HasIndex("IntegrationId", "SourceSysId");

                    b.ToTable("SyncFailures", "sync");
                });

            modelBuilder.Entity("ServiceNowCM.Domain.Entities.SyncJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long>("IntegrationId")
                        .HasColumnType("bigint");

                    b.Property<int>("LastCompletedOffset")
                        .HasColumnType("int");

                    b.Property<int>("LastCompletedPage")
                        .HasColumnType("int");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalFailed")
                        .HasColumnType("int");

                    b.Property<int>("TotalFetched")
                        .HasColumnType("int");

                    b.Property<int>("TotalProcessed")
                        .HasColumnType("int");

                    b.Property<int>("TotalSkipped")
                        .HasColumnType("int");

                    b.Property<int>("TotalSucceeded")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationId");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("SyncJobs", "sync");
                });

            modelBuilder.Entity("ServiceNowCM.Domain.Entities.SyncedRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentManagerRecordNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("ContentManagerRecordUri")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FirstSyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("IntegrationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastSyncedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceRecordNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceSysId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationId", "SourceSysId")
                        .IsUnique();

                    b.ToTable("SyncedRecords", "sync");
                });

            modelBuilder.Entity("ServiceNowCM.Domain.Entities.IntegrationConfiguration", b =>
                {
                    b.HasOne("ServiceNowCM.Domain.Entities.ContentManagerConnection", null)
                        .WithMany()
                        .HasForeignKey("ContentManagerConnectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ServiceNowCM.Domain.Entities.ServiceNowConnection", null)
                        .WithMany()
                        .HasForeignKey("ServiceNowConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ServiceNowCM.Domain.Entities.IntegrationField", b =>
                {
                    b.HasOne("ServiceNowCM.Domain.Entities.IntegrationConfiguration", "IntegrationConfiguration")
                        .WithMany("Fields")
                        .HasForeignKey("IntegrationConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntegrationConfiguration");
                });

            modelBuilder.Entity("ServiceNowCM.Domain.Entities.SyncFailure", b =>
                {
                    b.HasOne("ServiceNowCM.Domain.Entities.IntegrationConfiguration", "Integration")
                        .WithMany()
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceNowCM.Domain.Entities.SyncJob", "SyncJob")
                        .WithMany()
                        .HasForeignKey("SyncJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Integration");

                    b.Navigation("SyncJob");
                });

            modelBuilder.Entity("ServiceNowCM.Domain.Entities.SyncJob", b =>
                {
                    b.HasOne("ServiceNowCM.Domain.Entities.IntegrationConfiguration", "Integration")
                        .WithMany()
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Integration");
                });

            modelBuilder.Entity("ServiceNowCM.Domain.Entities.SyncedRecord", b =>
                {
                    b.HasOne("ServiceNowCM.Domain.Entities.IntegrationConfiguration", null)
                        .WithMany()
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServiceNowCM.Domain.Entities.IntegrationConfiguration", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
